DROP DATABASE IF EXISTS `BMS`;
CREATE DATABASE `BMS`;
USE `BMS`;
DROP TABLE IF EXISTS `book`;
CREATE TABLE `book` (
  `ISBN` VARCHAR(20) PRIMARY KEY NOT NULL,
  `title` TEXT NOT NULL,
  `author` VARCHAR(100) NOT NULL,
  `year_published` INT(11) NOT NULL,
  `price` INT(11) NOT NULL
);